export const ADD_TODO = 'ADDING TODO COMPLETED';
export const DELETE_TODO = 'DELETING TODO';
export const TOGGLE_TODO = 'TOGGLE A TODO';
export const ADD_TODO_STARTING = 'ADD TODO STARTING';
export const ADD_TODO_FAILED = 'ADD TODO FAILED';